### ISSUE TITLE
Impossible to start sentry after sentry-quotas installation

### ISSUE THREAD

**Issue by 42antoine** [getsentry/sentry-quotas#2]
abenevaut@tagada:~$ sudo pip install sentry-quotas
	Downloading/unpacking sentry-quotas
	  Downloading sentry-quotas-0.2.0.tar.gz
	  Running setup.py egg_info for package sentry-quotas
	
	    warning: no files found matching '*' under directory 'src/sentry_quotas/templates'
	    warning: no previously-included files matching '*~' found anywhere in distribution
	Requirement already satisfied (use --upgrade to upgrade): nydus in /usr/local/lib/python2.7/dist-packages/nydus-0.10.8-py2.7.egg (from sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): redis in /usr/local/lib/python2.7/dist-packages/redis-2.8.0-py2.7.egg (from sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): sentry>=5.0.0 in /usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg (from sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup>=3.2.1,<3.3.0 in /usr/local/lib/python2.7/dist-packages/BeautifulSoup-3.2.1-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): celery>=3.0.15,<3.1.0 in /usr/local/lib/python2.7/dist-packages/celery-3.0.25-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): cssutils>=0.9.9,<0.10.0 in /usr/local/lib/python2.7/dist-packages/cssutils-0.9.10-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): Django>=1.5.5,<1.6 in /usr/local/lib/python2.7/dist-packages/Django-1.5.11-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): django-celery>=3.0.11,<3.1.0 in /usr/local/lib/python2.7/dist-packages/django_celery-3.0.23-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): django-crispy-forms>=1.2.3,<1.3.0 in /usr/local/lib/python2.7/dist-packages/django_crispy_forms-1.2.8-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): django-paging>=0.2.4,<0.3.0 in /usr/local/lib/python2.7/dist-packages/django_paging-0.2.5-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): django-picklefield>=0.3.0,<0.4.0 in /usr/local/lib/python2.7/dist-packages/django_picklefield-0.3.1-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): django-social-auth>=0.7.28,<0.8.0 in /usr/local/lib/python2.7/dist-packages/django_social_auth-0.7.28-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): django-static-compiler>=0.3.0,<0.4.0 in /usr/local/lib/python2.7/dist-packages/django_static_compiler-0.3.3-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): django-templatetag-sugar>=0.1.0,<0.2.0 in /usr/local/lib/python2.7/dist-packages/django_templatetag_sugar-0.1-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): email-reply-parser>=0.2.0,<0.3.0 in /usr/local/lib/python2.7/dist-packages/email_reply_parser-0.2.0-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): gunicorn>=0.17.2,<0.18.0 in /usr/local/lib/python2.7/dist-packages/gunicorn-0.17.4-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): httpagentparser>=1.2.1,<1.3.0 in /usr/local/lib/python2.7/dist-packages/httpagentparser-1.2.2-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): logan>=0.5.8.2,<0.6.0 in /usr/local/lib/python2.7/dist-packages/logan-0.5.10-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.6.0,<1.7.0 in /usr/local/lib/python2.7/dist-packages/Pygments-1.6-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): pynliner>=0.4.0,<0.6.0 in /usr/local/lib/python2.7/dist-packages/pynliner-0.5.2-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=1.5.0,<2.0.0 in /usr/local/lib/python2.7/dist-packages/python_dateutil-1.5-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): python-memcached>=1.53,<2.0.0 in /usr/local/lib/python2.7/dist-packages/python_memcached-1.53-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): raven>=4.0.1 in /usr/local/lib/python2.7/dist-packages/raven-5.1.1-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): simplejson>=3.1.0,<3.4.0 in /usr/local/lib/python2.7/dist-packages/simplejson-3.3.3-py2.7-linux-x86_64.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): setproctitle>=1.1.7,<1.2.0 in /usr/local/lib/python2.7/dist-packages/setproctitle-1.1.8-py2.7-linux-x86_64.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): South==0.8.2 in /usr/local/lib/python2.7/dist-packages/South-0.8.2-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): urllib3>=1.7.1,<1.8.0 in /usr/local/lib/python2.7/dist-packages/urllib3-1.7.1-py2.7.egg (from sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): billiard>=2.7.3.34,<3.0 in /usr/local/lib/python2.7/dist-packages/billiard-2.7.3.34-py2.7-linux-x86_64.egg (from celery>=3.0.15,<3.1.0->sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): kombu>=2.5.15,<3.0 in /usr/local/lib/python2.7/dist-packages/kombu-2.5.16-py2.7.egg (from celery>=3.0.15,<3.1.0->sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): pytz>dev in /usr/local/lib/python2.7/dist-packages/pytz-2014.10-py2.7.egg (from django-celery>=3.0.11,<3.1.0->sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages/six-1.8.0-py2.7.egg (from django-picklefield>=0.3.0,<0.4.0->sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): oauth2>=1.5.167 in /usr/local/lib/python2.7/dist-packages/oauth2-1.5.211-py2.7.egg (from django-social-auth>=0.7.28,<0.8.0->sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): python-openid>=2.2 in /usr/local/lib/python2.7/dist-packages/python_openid-2.2.5-py2.7.egg (from django-social-auth>=0.7.28,<0.8.0->sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): anyjson>=0.3.3 in /usr/local/lib/python2.7/dist-packages/anyjson-0.3.3-py2.7.egg (from kombu>=2.5.15,<3.0->celery>=3.0.15,<3.1.0->sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): amqp>=1.0.13,<1.1.0 in /usr/local/lib/python2.7/dist-packages/amqp-1.0.13-py2.7.egg (from kombu>=2.5.15,<3.0->celery>=3.0.15,<3.1.0->sentry>=5.0.0->sentry-quotas)
	Requirement already satisfied (use --upgrade to upgrade): httplib2 in /usr/local/lib/python2.7/dist-packages/httplib2-0.9-py2.7.egg (from oauth2>=1.5.167->django-social-auth>=0.7.28,<0.8.0->sentry>=5.0.0->sentry-quotas)
	Installing collected packages: sentry-quotas
	  Running setup.py install for sentry-quotas
	
	    warning: no files found matching '*' under directory 'src/sentry_quotas/templates'
	    warning: no previously-included files matching '*~' found anywhere in distribution
	Successfully installed sentry-quotas
	Cleaning up...

Then

	abenevaut@tagada:~$ sudo sentry --config=/etc/sentry.conf.py start
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/logan-0.5.10-py2.7.egg/logan/runner.py", line 101, in settings_callback
	    'settings': settings,
	  File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/utils/runner.py", line 222, in initialize_app
	    from sentry.app import env
	  File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/app.py", line 27, in <module>
	    quotas = get_instance(settings.SENTRY_QUOTAS, settings.SENTRY_QUOTA_OPTIONS)
	  File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/app.py", line 22, in get_instance
	    cls = import_string(path)
	  File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/utils/imports.py", line 34, in import_string
	    result = _cache[path]
	TypeError: unhashable type: 'dict'

**Comment by dcramer** [comment]
This is builtin to Sentry and this package is no longer maintained.
